/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProduitNonTrouveRouteImport } from './routes/produit-non-trouve'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as BrandBrandIdRouteImport } from './routes/brand.$brandId'
import { Route as AppHistoriqueRouteImport } from './routes/_app.historique'
import { Route as AppFavorisRouteImport } from './routes/_app.favoris'
import { Route as AppCompteRouteImport } from './routes/_app.compte'
import { Route as AppCategoriesRouteImport } from './routes/_app.categories'
import { Route as AppCategoriesIndexRouteImport } from './routes/_app.categories.index'
import { Route as AppProduitIdRouteImport } from './routes/_app.produit.$id'
import { Route as AppMarqueBrandIdRouteImport } from './routes/_app.marque.$brandId'
import { Route as AppEntrepriseCompanyIdRouteImport } from './routes/_app.entreprise.$companyId'
import { Route as AppCategoriesSlugRouteImport } from './routes/_app.categories.$slug'

const ProduitNonTrouveRoute = ProduitNonTrouveRouteImport.update({
  id: '/produit-non-trouve',
  path: '/produit-non-trouve',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const BrandBrandIdRoute = BrandBrandIdRouteImport.update({
  id: '/brand/$brandId',
  path: '/brand/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoriqueRoute = AppHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AppRoute,
} as any)
const AppFavorisRoute = AppFavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => AppRoute,
} as any)
const AppCompteRoute = AppCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCategoriesRoute,
} as any)
const AppProduitIdRoute = AppProduitIdRouteImport.update({
  id: '/produit/$id',
  path: '/produit/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMarqueBrandIdRoute = AppMarqueBrandIdRouteImport.update({
  id: '/marque/$brandId',
  path: '/marque/$brandId',
  getParentRoute: () => AppRoute,
} as any)
const AppEntrepriseCompanyIdRoute = AppEntrepriseCompanyIdRouteImport.update({
  id: '/entreprise/$companyId',
  path: '/entreprise/$companyId',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesSlugRoute = AppCategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppCategoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/not-found': typeof NotFoundRoute
  '/onboarding': typeof OnboardingRoute
  '/produit-non-trouve': typeof ProduitNonTrouveRoute
  '/categories': typeof AppCategoriesRouteWithChildren
  '/compte': typeof AppCompteRoute
  '/favoris': typeof AppFavorisRoute
  '/historique': typeof AppHistoriqueRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/categories/$slug': typeof AppCategoriesSlugRoute
  '/entreprise/$companyId': typeof AppEntrepriseCompanyIdRoute
  '/marque/$brandId': typeof AppMarqueBrandIdRoute
  '/produit/$id': typeof AppProduitIdRoute
  '/categories/': typeof AppCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/not-found': typeof NotFoundRoute
  '/onboarding': typeof OnboardingRoute
  '/produit-non-trouve': typeof ProduitNonTrouveRoute
  '/compte': typeof AppCompteRoute
  '/favoris': typeof AppFavorisRoute
  '/historique': typeof AppHistoriqueRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/': typeof AppIndexRoute
  '/categories/$slug': typeof AppCategoriesSlugRoute
  '/entreprise/$companyId': typeof AppEntrepriseCompanyIdRoute
  '/marque/$brandId': typeof AppMarqueBrandIdRoute
  '/produit/$id': typeof AppProduitIdRoute
  '/categories': typeof AppCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/not-found': typeof NotFoundRoute
  '/onboarding': typeof OnboardingRoute
  '/produit-non-trouve': typeof ProduitNonTrouveRoute
  '/_app/categories': typeof AppCategoriesRouteWithChildren
  '/_app/compte': typeof AppCompteRoute
  '/_app/favoris': typeof AppFavorisRoute
  '/_app/historique': typeof AppHistoriqueRoute
  '/brand/$brandId': typeof BrandBrandIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/categories/$slug': typeof AppCategoriesSlugRoute
  '/_app/entreprise/$companyId': typeof AppEntrepriseCompanyIdRoute
  '/_app/marque/$brandId': typeof AppMarqueBrandIdRoute
  '/_app/produit/$id': typeof AppProduitIdRoute
  '/_app/categories/': typeof AppCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/not-found'
    | '/onboarding'
    | '/produit-non-trouve'
    | '/categories'
    | '/compte'
    | '/favoris'
    | '/historique'
    | '/brand/$brandId'
    | '/categories/$slug'
    | '/entreprise/$companyId'
    | '/marque/$brandId'
    | '/produit/$id'
    | '/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/not-found'
    | '/onboarding'
    | '/produit-non-trouve'
    | '/compte'
    | '/favoris'
    | '/historique'
    | '/brand/$brandId'
    | '/'
    | '/categories/$slug'
    | '/entreprise/$companyId'
    | '/marque/$brandId'
    | '/produit/$id'
    | '/categories'
  id:
    | '__root__'
    | '/_app'
    | '/not-found'
    | '/onboarding'
    | '/produit-non-trouve'
    | '/_app/categories'
    | '/_app/compte'
    | '/_app/favoris'
    | '/_app/historique'
    | '/brand/$brandId'
    | '/_app/'
    | '/_app/categories/$slug'
    | '/_app/entreprise/$companyId'
    | '/_app/marque/$brandId'
    | '/_app/produit/$id'
    | '/_app/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  NotFoundRoute: typeof NotFoundRoute
  OnboardingRoute: typeof OnboardingRoute
  ProduitNonTrouveRoute: typeof ProduitNonTrouveRoute
  BrandBrandIdRoute: typeof BrandBrandIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produit-non-trouve': {
      id: '/produit-non-trouve'
      path: '/produit-non-trouve'
      fullPath: '/produit-non-trouve'
      preLoaderRoute: typeof ProduitNonTrouveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/brand/$brandId': {
      id: '/brand/$brandId'
      path: '/brand/$brandId'
      fullPath: '/brand/$brandId'
      preLoaderRoute: typeof BrandBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/historique': {
      id: '/_app/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AppHistoriqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favoris': {
      id: '/_app/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof AppFavorisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compte': {
      id: '/_app/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AppCompteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/': {
      id: '/_app/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppCategoriesRoute
    }
    '/_app/produit/$id': {
      id: '/_app/produit/$id'
      path: '/produit/$id'
      fullPath: '/produit/$id'
      preLoaderRoute: typeof AppProduitIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marque/$brandId': {
      id: '/_app/marque/$brandId'
      path: '/marque/$brandId'
      fullPath: '/marque/$brandId'
      preLoaderRoute: typeof AppMarqueBrandIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entreprise/$companyId': {
      id: '/_app/entreprise/$companyId'
      path: '/entreprise/$companyId'
      fullPath: '/entreprise/$companyId'
      preLoaderRoute: typeof AppEntrepriseCompanyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/$slug': {
      id: '/_app/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof AppCategoriesSlugRouteImport
      parentRoute: typeof AppCategoriesRoute
    }
  }
}

interface AppCategoriesRouteChildren {
  AppCategoriesSlugRoute: typeof AppCategoriesSlugRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
}

const AppCategoriesRouteChildren: AppCategoriesRouteChildren = {
  AppCategoriesSlugRoute: AppCategoriesSlugRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
}

const AppCategoriesRouteWithChildren = AppCategoriesRoute._addFileChildren(
  AppCategoriesRouteChildren,
)

interface AppRouteChildren {
  AppCategoriesRoute: typeof AppCategoriesRouteWithChildren
  AppCompteRoute: typeof AppCompteRoute
  AppFavorisRoute: typeof AppFavorisRoute
  AppHistoriqueRoute: typeof AppHistoriqueRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEntrepriseCompanyIdRoute: typeof AppEntrepriseCompanyIdRoute
  AppMarqueBrandIdRoute: typeof AppMarqueBrandIdRoute
  AppProduitIdRoute: typeof AppProduitIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriesRoute: AppCategoriesRouteWithChildren,
  AppCompteRoute: AppCompteRoute,
  AppFavorisRoute: AppFavorisRoute,
  AppHistoriqueRoute: AppHistoriqueRoute,
  AppIndexRoute: AppIndexRoute,
  AppEntrepriseCompanyIdRoute: AppEntrepriseCompanyIdRoute,
  AppMarqueBrandIdRoute: AppMarqueBrandIdRoute,
  AppProduitIdRoute: AppProduitIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  NotFoundRoute: NotFoundRoute,
  OnboardingRoute: OnboardingRoute,
  ProduitNonTrouveRoute: ProduitNonTrouveRoute,
  BrandBrandIdRoute: BrandBrandIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
