/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppFavorisRouteImport } from './routes/_app.favoris'
import { Route as AppProduitIdRouteImport } from './routes/_app.produit.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFavorisRoute = AppFavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => AppRoute,
} as any)
const AppProduitIdRoute = AppProduitIdRouteImport.update({
  id: '/produit/$id',
  path: '/produit/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/favoris': typeof AppFavorisRoute
  '/produit/$id': typeof AppProduitIdRoute
}
export interface FileRoutesByTo {
  '/favoris': typeof AppFavorisRoute
  '/': typeof AppIndexRoute
  '/produit/$id': typeof AppProduitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/favoris': typeof AppFavorisRoute
  '/_app/': typeof AppIndexRoute
  '/_app/produit/$id': typeof AppProduitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favoris' | '/produit/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/favoris' | '/' | '/produit/$id'
  id: '__root__' | '/_app' | '/_app/favoris' | '/_app/' | '/_app/produit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favoris': {
      id: '/_app/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof AppFavorisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produit/$id': {
      id: '/_app/produit/$id'
      path: '/produit/$id'
      fullPath: '/produit/$id'
      preLoaderRoute: typeof AppProduitIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFavorisRoute: typeof AppFavorisRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProduitIdRoute: typeof AppProduitIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFavorisRoute: AppFavorisRoute,
  AppIndexRoute: AppIndexRoute,
  AppProduitIdRoute: AppProduitIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
